[package]
name = "schiro"
version = "0.1.0"
edition = "2021"
publish = false

[dev-dependencies]
schiro-ast = { path = "crates/schiro-ast" }
schiro-lexer = { path = "crates/schiro-lexer" }
schiro-parser = { path = "crates/schiro-parser" }
schiro-semantic = { path = "crates/schiro-semantic" }

[workspace]
resolver = "2"
members = [
    "crates/schiro-ast",
    "crates/schiro-lexer",
    "crates/schiro-parser",
    "crates/schiro-semantic",
    "crates/schiro-codegen",
    "crates/schiro-cli",
]
